// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc6iknW0SAX5TN5Cg5UY_WfxjI2rg6e4U',
    appId: '1:700059930357:web:dab00066674757896cffbc',
    messagingSenderId: '700059930357',
    projectId: 'helapfe',
    authDomain: 'helapfe.firebaseapp.com',
    databaseURL: 'https://helapfe-default-rtdb.firebaseio.com',
    storageBucket: 'helapfe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa0qgWC6saA3UME1alcrlTulgKXEVHwhg',
    appId: '1:700059930357:android:3478cb3638e05bf26cffbc',
    messagingSenderId: '700059930357',
    projectId: 'helapfe',
    databaseURL: 'https://helapfe-default-rtdb.firebaseio.com',
    storageBucket: 'helapfe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlpjanvcwUf_C6b7ZDJrUWXKIMSNJfDTQ',
    appId: '1:700059930357:ios:092af47e0a3e78fc6cffbc',
    messagingSenderId: '700059930357',
    projectId: 'helapfe',
    databaseURL: 'https://helapfe-default-rtdb.firebaseio.com',
    storageBucket: 'helapfe.appspot.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlpjanvcwUf_C6b7ZDJrUWXKIMSNJfDTQ',
    appId: '1:700059930357:ios:092af47e0a3e78fc6cffbc',
    messagingSenderId: '700059930357',
    projectId: 'helapfe',
    databaseURL: 'https://helapfe-default-rtdb.firebaseio.com',
    storageBucket: 'helapfe.appspot.com',
    iosBundleId: 'com.example.pfe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCc6iknW0SAX5TN5Cg5UY_WfxjI2rg6e4U',
    appId: '1:700059930357:web:4ba42c1fea2040e66cffbc',
    messagingSenderId: '700059930357',
    projectId: 'helapfe',
    authDomain: 'helapfe.firebaseapp.com',
    databaseURL: 'https://helapfe-default-rtdb.firebaseio.com',
    storageBucket: 'helapfe.appspot.com',
  );
}
